---
development:
  cloud_name: ENV['cloud_name']
  api_key: ENV['cloudinary_key']
  api_secret: ENV['cloudinary_secret']
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: ENV['cloud_name']
  api_key: ENV['cloudinary_key']
  api_secret: ENV['cloudinary_secret']
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: ENV['cloud_name']
  api_key: ENV['cloudinary_key']
  api_secret: ENV['cloudinary_secret']
  enhance_image_tag: true
  static_image_support: false
